image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - push

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build_image:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE/simple-app:latest .
    - docker save $CI_REGISTRY_IMAGE/simple-app:latest -o simple-app.tar
  artifacts:
    paths:
      - simple-app.tar
    expire_in: 30 min

push_image:
  stage: push
  script:
    - docker load -i simple-app.tar
    - docker push $CI_REGISTRY_IMAGE/simple-app:latest
  only:
    - main